# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy To UAT Env

on:
  push:
    branches: ['main']

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy_uat:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment:
      name: uat
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Deploy to Sirius Env
        run: npm run deploy
        env:
          ENV: uat
